package main

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPart1(t *testing.T) {
	t.Parallel()
	// Config

	// Test Cases
	tests := map[string]struct {
		input    string
		expected int
		repeat   bool
	}{
		"ex1": {
			input: `..........
						..........
						..........
						....a.....
						..........
						.....a....
						..........
						..........
						..........
						..........`,
			expected: 2,
		},
		"ex2": {
			input: `..........
				...#......
				#.........
				....a.....
				........a.
				.....a....
				..#.......
				......#...
				..........
				..........`,
			expected: 4,
		},
		"ex4": {
			input: `............
		........0...
		.....0......
		.......0....
		....0.......
		......A.....
		............
		............
		........A...
		.........A..
		............
		............`,
			expected: 14,
		},
		"r1": {
			input: `T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........`,
			expected: 9,
			repeat:   true,
		},
	}

	// Testing
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			actual := nodes(test.input, test.repeat)
			require.Equal(t, test.expected, actual)
		})
	}
}
